/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as EasterEggRouteImport } from './routes/easter-egg'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MindfulnessRouteImport } from './routes/mindfulness'
import { Route as MyPictariaRouteImport } from './routes/my-pictaria'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ShareRouteImport } from './routes/share'
import { Route as VisionBoardRouteImport } from './routes/vision-board'
import { Route as WorkLifeBalanceRouteImport } from './routes/work-life-balance'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CollectionCollectionIdRouteImport } from './routes/collection.$collectionId'
import { Route as MyPictariaIndexRouteImport } from './routes/my-pictaria.index'
import { Route as MyPictariaSubmittedRouteImport } from './routes/my-pictaria.submitted'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalIdRouteImport } from './routes/portal.$id'
import { Route as PortalBetaRouteImport } from './routes/portal.beta'
import { Route as PortalCommunityRouteImport } from './routes/portal.community'
import { Route as PortalDailyRouteImport } from './routes/portal.daily'
import { Route as PortalDailyPastRouteImport } from './routes/portal.daily-past'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalLibraryRouteImport } from './routes/portal.library'
import { Route as PortalNewRouteImport } from './routes/portal.new'
import { Route as PortalPushRouteImport } from './routes/portal.push'
import { Route as PortalSubscribersRouteImport } from './routes/portal.subscribers'
import { Route as PuzzlePuzzleIdRouteImport } from './routes/puzzle.$puzzleId'
import { Route as StorybookCollectionIdRouteImport } from './routes/storybook.$collectionId'
import { Route as StudioArtistRouteImport } from './routes/studio.artist'
import { Route as StudioBrandRouteImport } from './routes/studio.brand'
import { Route as StudioPersonalRouteImport } from './routes/studio.personal'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicPushMedleyRouteImport } from './routes/api/public/push-medley'
import { Route as PortalLibraryCollectionIdRouteImport } from './routes/portal.library.$collectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const EasterEggRoute = EasterEggRouteImport.update({
  id: '/easter-egg',
  path: '/easter-egg',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulnessRoute = MindfulnessRouteImport.update({
  id: '/mindfulness',
  path: '/mindfulness',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPictariaRoute = MyPictariaRouteImport.update({
  id: '/my-pictaria',
  path: '/my-pictaria',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionBoardRoute = VisionBoardRouteImport.update({
  id: '/vision-board',
  path: '/vision-board',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLifeBalanceRoute = WorkLifeBalanceRouteImport.update({
  id: '/work-life-balance',
  path: '/work-life-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionCollectionIdRoute = CollectionCollectionIdRouteImport.update({
  id: '/collection/$collectionId',
  path: '/collection/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPictariaIndexRoute = MyPictariaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyPictariaRoute,
} as any)
const MyPictariaSubmittedRoute = MyPictariaSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => MyPictariaRoute,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIdRoute = PortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBetaRoute = PortalBetaRouteImport.update({
  id: '/portal/beta',
  path: '/portal/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCommunityRoute = PortalCommunityRouteImport.update({
  id: '/portal/community',
  path: '/portal/community',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDailyRoute = PortalDailyRouteImport.update({
  id: '/portal/daily',
  path: '/portal/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDailyPastRoute = PortalDailyPastRouteImport.update({
  id: '/portal/daily-past',
  path: '/portal/daily-past',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLibraryRoute = PortalLibraryRouteImport.update({
  id: '/portal/library',
  path: '/portal/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNewRoute = PortalNewRouteImport.update({
  id: '/portal/new',
  path: '/portal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPushRoute = PortalPushRouteImport.update({
  id: '/portal/push',
  path: '/portal/push',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSubscribersRoute = PortalSubscribersRouteImport.update({
  id: '/portal/subscribers',
  path: '/portal/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlePuzzleIdRoute = PuzzlePuzzleIdRouteImport.update({
  id: '/puzzle/$puzzleId',
  path: '/puzzle/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookCollectionIdRoute = StorybookCollectionIdRouteImport.update({
  id: '/storybook/$collectionId',
  path: '/storybook/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioArtistRoute = StudioArtistRouteImport.update({
  id: '/studio/artist',
  path: '/studio/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBrandRoute = StudioBrandRouteImport.update({
  id: '/studio/brand',
  path: '/studio/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPersonalRoute = StudioPersonalRouteImport.update({
  id: '/studio/personal',
  path: '/studio/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushMedleyRoute = ApiPublicPushMedleyRouteImport.update({
  id: '/api/public/push-medley',
  path: '/api/public/push-medley',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLibraryCollectionIdRoute =
  PortalLibraryCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => PortalLibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/easter-egg': typeof EasterEggRoute
  '/launch': typeof LaunchRoute
  '/mcp': typeof McpRoute
  '/mindfulness': typeof MindfulnessRoute
  '/my-pictaria': typeof MyPictariaRouteWithChildren
  '/pricing': typeof PricingRoute
  '/share': typeof ShareRoute
  '/vision-board': typeof VisionBoardRoute
  '/work-life-balance': typeof WorkLifeBalanceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/my-pictaria/submitted': typeof MyPictariaSubmittedRoute
  '/p/$code': typeof PCodeRoute
  '/portal/$id': typeof PortalIdRoute
  '/portal/beta': typeof PortalBetaRoute
  '/portal/community': typeof PortalCommunityRoute
  '/portal/daily': typeof PortalDailyRoute
  '/portal/daily-past': typeof PortalDailyPastRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/library': typeof PortalLibraryRouteWithChildren
  '/portal/new': typeof PortalNewRoute
  '/portal/push': typeof PortalPushRoute
  '/portal/subscribers': typeof PortalSubscribersRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/storybook/$collectionId': typeof StorybookCollectionIdRoute
  '/studio/artist': typeof StudioArtistRoute
  '/studio/brand': typeof StudioBrandRoute
  '/studio/personal': typeof StudioPersonalRoute
  '/my-pictaria/': typeof MyPictariaIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/push-medley': typeof ApiPublicPushMedleyRoute
  '/portal/library/$collectionId': typeof PortalLibraryCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/easter-egg': typeof EasterEggRoute
  '/launch': typeof LaunchRoute
  '/mcp': typeof McpRoute
  '/mindfulness': typeof MindfulnessRoute
  '/pricing': typeof PricingRoute
  '/share': typeof ShareRoute
  '/vision-board': typeof VisionBoardRoute
  '/work-life-balance': typeof WorkLifeBalanceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/my-pictaria/submitted': typeof MyPictariaSubmittedRoute
  '/p/$code': typeof PCodeRoute
  '/portal/$id': typeof PortalIdRoute
  '/portal/beta': typeof PortalBetaRoute
  '/portal/community': typeof PortalCommunityRoute
  '/portal/daily': typeof PortalDailyRoute
  '/portal/daily-past': typeof PortalDailyPastRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/library': typeof PortalLibraryRouteWithChildren
  '/portal/new': typeof PortalNewRoute
  '/portal/push': typeof PortalPushRoute
  '/portal/subscribers': typeof PortalSubscribersRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/storybook/$collectionId': typeof StorybookCollectionIdRoute
  '/studio/artist': typeof StudioArtistRoute
  '/studio/brand': typeof StudioBrandRoute
  '/studio/personal': typeof StudioPersonalRoute
  '/my-pictaria': typeof MyPictariaIndexRoute
  '/portal': typeof PortalIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/push-medley': typeof ApiPublicPushMedleyRoute
  '/portal/library/$collectionId': typeof PortalLibraryCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/easter-egg': typeof EasterEggRoute
  '/launch': typeof LaunchRoute
  '/mcp': typeof McpRoute
  '/mindfulness': typeof MindfulnessRoute
  '/my-pictaria': typeof MyPictariaRouteWithChildren
  '/pricing': typeof PricingRoute
  '/share': typeof ShareRoute
  '/vision-board': typeof VisionBoardRoute
  '/work-life-balance': typeof WorkLifeBalanceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/my-pictaria/submitted': typeof MyPictariaSubmittedRoute
  '/p/$code': typeof PCodeRoute
  '/portal/$id': typeof PortalIdRoute
  '/portal/beta': typeof PortalBetaRoute
  '/portal/community': typeof PortalCommunityRoute
  '/portal/daily': typeof PortalDailyRoute
  '/portal/daily-past': typeof PortalDailyPastRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/library': typeof PortalLibraryRouteWithChildren
  '/portal/new': typeof PortalNewRoute
  '/portal/push': typeof PortalPushRoute
  '/portal/subscribers': typeof PortalSubscribersRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/storybook/$collectionId': typeof StorybookCollectionIdRoute
  '/studio/artist': typeof StudioArtistRoute
  '/studio/brand': typeof StudioBrandRoute
  '/studio/personal': typeof StudioPersonalRoute
  '/my-pictaria/': typeof MyPictariaIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/push-medley': typeof ApiPublicPushMedleyRoute
  '/portal/library/$collectionId': typeof PortalLibraryCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/beta'
    | '/collections'
    | '/create'
    | '/daily'
    | '/easter-egg'
    | '/launch'
    | '/mcp'
    | '/mindfulness'
    | '/my-pictaria'
    | '/pricing'
    | '/share'
    | '/vision-board'
    | '/work-life-balance'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/collection/$collectionId'
    | '/my-pictaria/submitted'
    | '/p/$code'
    | '/portal/$id'
    | '/portal/beta'
    | '/portal/community'
    | '/portal/daily'
    | '/portal/daily-past'
    | '/portal/dashboard'
    | '/portal/library'
    | '/portal/new'
    | '/portal/push'
    | '/portal/subscribers'
    | '/puzzle/$puzzleId'
    | '/storybook/$collectionId'
    | '/studio/artist'
    | '/studio/brand'
    | '/studio/personal'
    | '/my-pictaria/'
    | '/portal/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/push-medley'
    | '/portal/library/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/beta'
    | '/collections'
    | '/create'
    | '/daily'
    | '/easter-egg'
    | '/launch'
    | '/mcp'
    | '/mindfulness'
    | '/pricing'
    | '/share'
    | '/vision-board'
    | '/work-life-balance'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/collection/$collectionId'
    | '/my-pictaria/submitted'
    | '/p/$code'
    | '/portal/$id'
    | '/portal/beta'
    | '/portal/community'
    | '/portal/daily'
    | '/portal/daily-past'
    | '/portal/dashboard'
    | '/portal/library'
    | '/portal/new'
    | '/portal/push'
    | '/portal/subscribers'
    | '/puzzle/$puzzleId'
    | '/storybook/$collectionId'
    | '/studio/artist'
    | '/studio/brand'
    | '/studio/personal'
    | '/my-pictaria'
    | '/portal'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/push-medley'
    | '/portal/library/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/beta'
    | '/collections'
    | '/create'
    | '/daily'
    | '/easter-egg'
    | '/launch'
    | '/mcp'
    | '/mindfulness'
    | '/my-pictaria'
    | '/pricing'
    | '/share'
    | '/vision-board'
    | '/work-life-balance'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/collection/$collectionId'
    | '/my-pictaria/submitted'
    | '/p/$code'
    | '/portal/$id'
    | '/portal/beta'
    | '/portal/community'
    | '/portal/daily'
    | '/portal/daily-past'
    | '/portal/dashboard'
    | '/portal/library'
    | '/portal/new'
    | '/portal/push'
    | '/portal/subscribers'
    | '/puzzle/$puzzleId'
    | '/storybook/$collectionId'
    | '/studio/artist'
    | '/studio/brand'
    | '/studio/personal'
    | '/my-pictaria/'
    | '/portal/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/push-medley'
    | '/portal/library/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BetaRoute: typeof BetaRoute
  CollectionsRoute: typeof CollectionsRoute
  CreateRoute: typeof CreateRoute
  DailyRoute: typeof DailyRoute
  EasterEggRoute: typeof EasterEggRoute
  LaunchRoute: typeof LaunchRoute
  McpRoute: typeof McpRoute
  MindfulnessRoute: typeof MindfulnessRoute
  MyPictariaRoute: typeof MyPictariaRouteWithChildren
  PricingRoute: typeof PricingRoute
  ShareRoute: typeof ShareRoute
  VisionBoardRoute: typeof VisionBoardRoute
  WorkLifeBalanceRoute: typeof WorkLifeBalanceRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CollectionCollectionIdRoute: typeof CollectionCollectionIdRoute
  PCodeRoute: typeof PCodeRoute
  PortalIdRoute: typeof PortalIdRoute
  PortalBetaRoute: typeof PortalBetaRoute
  PortalCommunityRoute: typeof PortalCommunityRoute
  PortalDailyRoute: typeof PortalDailyRoute
  PortalDailyPastRoute: typeof PortalDailyPastRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLibraryRoute: typeof PortalLibraryRouteWithChildren
  PortalNewRoute: typeof PortalNewRoute
  PortalPushRoute: typeof PortalPushRoute
  PortalSubscribersRoute: typeof PortalSubscribersRoute
  PuzzlePuzzleIdRoute: typeof PuzzlePuzzleIdRoute
  StorybookCollectionIdRoute: typeof StorybookCollectionIdRoute
  StudioArtistRoute: typeof StudioArtistRoute
  StudioBrandRoute: typeof StudioBrandRoute
  StudioPersonalRoute: typeof StudioPersonalRoute
  PortalIndexRoute: typeof PortalIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPushMedleyRoute: typeof ApiPublicPushMedleyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easter-egg': {
      id: '/easter-egg'
      path: '/easter-egg'
      fullPath: '/easter-egg'
      preLoaderRoute: typeof EasterEggRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindfulness': {
      id: '/mindfulness'
      path: '/mindfulness'
      fullPath: '/mindfulness'
      preLoaderRoute: typeof MindfulnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pictaria': {
      id: '/my-pictaria'
      path: '/my-pictaria'
      fullPath: '/my-pictaria'
      preLoaderRoute: typeof MyPictariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-board': {
      id: '/vision-board'
      path: '/vision-board'
      fullPath: '/vision-board'
      preLoaderRoute: typeof VisionBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-life-balance': {
      id: '/work-life-balance'
      path: '/work-life-balance'
      fullPath: '/work-life-balance'
      preLoaderRoute: typeof WorkLifeBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$collectionId': {
      id: '/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/collection/$collectionId'
      preLoaderRoute: typeof CollectionCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pictaria/': {
      id: '/my-pictaria/'
      path: '/'
      fullPath: '/my-pictaria/'
      preLoaderRoute: typeof MyPictariaIndexRouteImport
      parentRoute: typeof MyPictariaRoute
    }
    '/my-pictaria/submitted': {
      id: '/my-pictaria/submitted'
      path: '/submitted'
      fullPath: '/my-pictaria/submitted'
      preLoaderRoute: typeof MyPictariaSubmittedRouteImport
      parentRoute: typeof MyPictariaRoute
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$id': {
      id: '/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof PortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/beta': {
      id: '/portal/beta'
      path: '/portal/beta'
      fullPath: '/portal/beta'
      preLoaderRoute: typeof PortalBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/community': {
      id: '/portal/community'
      path: '/portal/community'
      fullPath: '/portal/community'
      preLoaderRoute: typeof PortalCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/daily': {
      id: '/portal/daily'
      path: '/portal/daily'
      fullPath: '/portal/daily'
      preLoaderRoute: typeof PortalDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/daily-past': {
      id: '/portal/daily-past'
      path: '/portal/daily-past'
      fullPath: '/portal/daily-past'
      preLoaderRoute: typeof PortalDailyPastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/library': {
      id: '/portal/library'
      path: '/portal/library'
      fullPath: '/portal/library'
      preLoaderRoute: typeof PortalLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/new': {
      id: '/portal/new'
      path: '/portal/new'
      fullPath: '/portal/new'
      preLoaderRoute: typeof PortalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/push': {
      id: '/portal/push'
      path: '/portal/push'
      fullPath: '/portal/push'
      preLoaderRoute: typeof PortalPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/subscribers': {
      id: '/portal/subscribers'
      path: '/portal/subscribers'
      fullPath: '/portal/subscribers'
      preLoaderRoute: typeof PortalSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$puzzleId': {
      id: '/puzzle/$puzzleId'
      path: '/puzzle/$puzzleId'
      fullPath: '/puzzle/$puzzleId'
      preLoaderRoute: typeof PuzzlePuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook/$collectionId': {
      id: '/storybook/$collectionId'
      path: '/storybook/$collectionId'
      fullPath: '/storybook/$collectionId'
      preLoaderRoute: typeof StorybookCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/artist': {
      id: '/studio/artist'
      path: '/studio/artist'
      fullPath: '/studio/artist'
      preLoaderRoute: typeof StudioArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/brand': {
      id: '/studio/brand'
      path: '/studio/brand'
      fullPath: '/studio/brand'
      preLoaderRoute: typeof StudioBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/personal': {
      id: '/studio/personal'
      path: '/studio/personal'
      fullPath: '/studio/personal'
      preLoaderRoute: typeof StudioPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-medley': {
      id: '/api/public/push-medley'
      path: '/api/public/push-medley'
      fullPath: '/api/public/push-medley'
      preLoaderRoute: typeof ApiPublicPushMedleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/library/$collectionId': {
      id: '/portal/library/$collectionId'
      path: '/$collectionId'
      fullPath: '/portal/library/$collectionId'
      preLoaderRoute: typeof PortalLibraryCollectionIdRouteImport
      parentRoute: typeof PortalLibraryRoute
    }
  }
}

interface MyPictariaRouteChildren {
  MyPictariaSubmittedRoute: typeof MyPictariaSubmittedRoute
  MyPictariaIndexRoute: typeof MyPictariaIndexRoute
}

const MyPictariaRouteChildren: MyPictariaRouteChildren = {
  MyPictariaSubmittedRoute: MyPictariaSubmittedRoute,
  MyPictariaIndexRoute: MyPictariaIndexRoute,
}

const MyPictariaRouteWithChildren = MyPictariaRoute._addFileChildren(
  MyPictariaRouteChildren,
)

interface PortalLibraryRouteChildren {
  PortalLibraryCollectionIdRoute: typeof PortalLibraryCollectionIdRoute
}

const PortalLibraryRouteChildren: PortalLibraryRouteChildren = {
  PortalLibraryCollectionIdRoute: PortalLibraryCollectionIdRoute,
}

const PortalLibraryRouteWithChildren = PortalLibraryRoute._addFileChildren(
  PortalLibraryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BetaRoute: BetaRoute,
  CollectionsRoute: CollectionsRoute,
  CreateRoute: CreateRoute,
  DailyRoute: DailyRoute,
  EasterEggRoute: EasterEggRoute,
  LaunchRoute: LaunchRoute,
  McpRoute: McpRoute,
  MindfulnessRoute: MindfulnessRoute,
  MyPictariaRoute: MyPictariaRouteWithChildren,
  PricingRoute: PricingRoute,
  ShareRoute: ShareRoute,
  VisionBoardRoute: VisionBoardRoute,
  WorkLifeBalanceRoute: WorkLifeBalanceRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CollectionCollectionIdRoute: CollectionCollectionIdRoute,
  PCodeRoute: PCodeRoute,
  PortalIdRoute: PortalIdRoute,
  PortalBetaRoute: PortalBetaRoute,
  PortalCommunityRoute: PortalCommunityRoute,
  PortalDailyRoute: PortalDailyRoute,
  PortalDailyPastRoute: PortalDailyPastRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLibraryRoute: PortalLibraryRouteWithChildren,
  PortalNewRoute: PortalNewRoute,
  PortalPushRoute: PortalPushRoute,
  PortalSubscribersRoute: PortalSubscribersRoute,
  PuzzlePuzzleIdRoute: PuzzlePuzzleIdRoute,
  StorybookCollectionIdRoute: StorybookCollectionIdRoute,
  StudioArtistRoute: StudioArtistRoute,
  StudioBrandRoute: StudioBrandRoute,
  StudioPersonalRoute: StudioPersonalRoute,
  PortalIndexRoute: PortalIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPushMedleyRoute: ApiPublicPushMedleyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
