/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionCollectionIdRouteImport } from './routes/collection.$collectionId'
import { Route as PuzzlePuzzleIdRouteImport } from './routes/puzzle.$puzzleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionCollectionIdRoute = CollectionCollectionIdRouteImport.update({
  id: '/collection/$collectionId',
  path: '/collection/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlePuzzleIdRoute = PuzzlePuzzleIdRouteImport.update({
  id: '/puzzle/$puzzleId',
  path: '/puzzle/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection/$collectionId' | '/puzzle/$puzzleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection/$collectionId' | '/puzzle/$puzzleId'
  id: '__root__' | '/' | '/collection/$collectionId' | '/puzzle/$puzzleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionCollectionIdRoute: typeof CollectionCollectionIdRoute
  PuzzlePuzzleIdRoute: typeof PuzzlePuzzleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$collectionId': {
      id: '/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/collection/$collectionId'
      preLoaderRoute: typeof CollectionCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$puzzleId': {
      id: '/puzzle/$puzzleId'
      path: '/puzzle/$puzzleId'
      fullPath: '/puzzle/$puzzleId'
      preLoaderRoute: typeof PuzzlePuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionCollectionIdRoute: CollectionCollectionIdRoute,
  PuzzlePuzzleIdRoute: PuzzlePuzzleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
