/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CollectionCollectionIdRouteImport } from './routes/collection.$collectionId'
import { Route as PuzzlePuzzleIdRouteImport } from './routes/puzzle.$puzzleId'
import { Route as StorybookCollectionIdRouteImport } from './routes/storybook.$collectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionCollectionIdRoute = CollectionCollectionIdRouteImport.update({
  id: '/collection/$collectionId',
  path: '/collection/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlePuzzleIdRoute = PuzzlePuzzleIdRouteImport.update({
  id: '/puzzle/$puzzleId',
  path: '/puzzle/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookCollectionIdRoute = StorybookCollectionIdRouteImport.update({
  id: '/storybook/$collectionId',
  path: '/storybook/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/storybook/$collectionId': typeof StorybookCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/storybook/$collectionId': typeof StorybookCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/collection/$collectionId': typeof CollectionCollectionIdRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/storybook/$collectionId': typeof StorybookCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/collections'
    | '/create'
    | '/daily'
    | '/collection/$collectionId'
    | '/puzzle/$puzzleId'
    | '/storybook/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/collections'
    | '/create'
    | '/daily'
    | '/collection/$collectionId'
    | '/puzzle/$puzzleId'
    | '/storybook/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/collections'
    | '/create'
    | '/daily'
    | '/collection/$collectionId'
    | '/puzzle/$puzzleId'
    | '/storybook/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CollectionsRoute: typeof CollectionsRoute
  CreateRoute: typeof CreateRoute
  DailyRoute: typeof DailyRoute
  CollectionCollectionIdRoute: typeof CollectionCollectionIdRoute
  PuzzlePuzzleIdRoute: typeof PuzzlePuzzleIdRoute
  StorybookCollectionIdRoute: typeof StorybookCollectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$collectionId': {
      id: '/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/collection/$collectionId'
      preLoaderRoute: typeof CollectionCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$puzzleId': {
      id: '/puzzle/$puzzleId'
      path: '/puzzle/$puzzleId'
      fullPath: '/puzzle/$puzzleId'
      preLoaderRoute: typeof PuzzlePuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook/$collectionId': {
      id: '/storybook/$collectionId'
      path: '/storybook/$collectionId'
      fullPath: '/storybook/$collectionId'
      preLoaderRoute: typeof StorybookCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CollectionsRoute: CollectionsRoute,
  CreateRoute: CreateRoute,
  DailyRoute: DailyRoute,
  CollectionCollectionIdRoute: CollectionCollectionIdRoute,
  PuzzlePuzzleIdRoute: PuzzlePuzzleIdRoute,
  StorybookCollectionIdRoute: StorybookCollectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
